### PR TITLE
AdaBelief bias correction and epsilon

### PR DESCRIPTION
**Pull request by cossio**
Cf https://github.com/FluxML/Flux.jl/pull/1963

CC @mcabbott @darsnack

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]

**Comment by ToucheSir** [comment]
Thanks!

**Comment by cossio** [comment]
Thanks. Can we tag a release with this?

**Comment by ToucheSir** [comment]
https://github.com/JuliaRegistries/General/pull/60041

**Comment by cossio** [comment]
Thanks!

**Pull request merged**
